---
title: "<p align='center'> Sarvani Vajjala </p>"
logo: "/assets/img/sarvani.jpg"

description: |
  <p align="center">
    <a href="Sarvani_Vajjala_Resume (2).pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/sarvani-vvss/">LinkedIn</a> |
    <a href="https://github.com/sarvanivvss">GitHub</a>
  </p>
  <br>   
  <p>
    I'm acquiring hands-on knowledge in Data Science, Big Data, Spark, Machine learning & NLP related problems.
    Working as a Middleware developer with 10 years of experience.
  </p>

theme: jekyll-theme-minimal
---

<!DOCTYPE html>
<html>
<head>
  <!-- Add any head elements if necessary -->
</head>
<body>
  <!-- Your page content goes here -->
  <p>Your page content...</p>

  <!-- The corrected HTML section -->
  <p align="center"> Sarvani Vajjala </p>
  <img src="/assets/img/sarvani.jpg" alt="Sarvani's Logo">

  <p align="center">
    <a href="Sarvani_Vajjala_Resume (2).pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/sarvani-vvss/">LinkedIn</a> |
    <a href="https://github.com/sarvanivvss">GitHub</a>
  </p>
  <br>   
  <p>
    I'm acquiring hands-on knowledge in Data Science, Big Data, Spark, Machine learning & NLP related problems.
    Working as a Middleware developer with 10 years of experience.
  </p>

  <!-- Add any additional content or structure as needed -->

  <!-- Your page footer goes here -->
</body>
</html>
