title: <p align="center"> Sarvani Vajjala </p>
logo: /assets/img/sarvani.jpg

description:
  <p align="center">
  <a href="Sarvani_Vajjala_Resume (2).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sarvani-vvss">LinkedIn</a> |
  <a href="https://github.com/sarvanivvss">GitHub</a>
  
  <br>   
  I'm acquiring hands on knowledge on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Working as a Middleware developer, has 10 years of experience
  <br>
  </p>



theme: jekyll-theme-minimal
